### ISSUE TITLE
Q: is doxylink able to link in a latex environment, example?

### ISSUE THREAD

**Issue by SteinHeselmans** [sphinx-contrib/doxylink#17]
Did anyone ever try to use doxylink in a latex environment in order to generate a PDF from RST documentation? If so, what should be the minimal doxyfile and sphinx configuration? Maybe the example in this project can be extended for latex output?

I tried enabling GENERATE_LATEX in my doxyfile, that generates a bunch of tex and pdf-files, amongst with the tag file which doxylink uses to lookup the links. The links that doxylink generates are links to html files.

**Comment by milliams** [comment]
To-date, it has only been used for linking against HTML documentation. When you enable `GENERATE_LATEX`, does the tag XML file give in-PDF links? I'm not sure if there's a standard format for how to link to elements inside a PDF document or whether each PDF reader does it its own way.

**Comment by SteinHeselmans** [comment]
ah no, the tag-file still gives html files for <anchorfile> and hashes (or what are those?) for <anchor>, probably i first need to get some latex information there before looking at doxylink project...

I don't know if you're familiar with the setup, so on high level: sphinx generates tex-files (latex) which contain latex links in between them. After that pdflatex (or another tool) converts the tex-files to a pdf.

I looked a bit closer at the generated tex and pdf files of doxygen: the pdf-files are the images which are included in the textual tex-files.

**Comment by SteinHeselmans** [comment]
as an alternative, i tried using breathe (https://github.com/michaeljones/breathe) which generates an inline copy of the doxygen documentation. It works ok on my PDF build. So now i am using a combination of doxy-link and breathe directives...
