### ISSUE TITLE
Support remote tag files that don't return a last-modified header

### ISSUE THREAD

**Issue by duncanmmacleod** [sphinx-contrib/doxylink#30]
I'm trying to use `sphinxcontrib-doxylink` with a remote tag file for which the host server doesn't include a `Last-Modified` header in the HTTP response. Is it a reasonable patch to this module to use the `Expires` header* as a backup in these cases?

*I originally thought `Date` would make more sense, but `Expires` would project a new tag file into the future enough that repeated execution will effectively use the cached version for as long as the `Cache-Control` header tells it to.

Am happy to propose a patch in a PR if one would be welcome.

**Comment by milliams** [comment]
Hi Duncan,

I think that using `Expires` as a fall-back header would make sense. It's really all just to avoid repeatedly having to parse the file for every documentation build while working on it. It only has to be coarse-grained.

A PR would be welcome.

**Comment by duncanmmacleod** [comment]
@milliams, thanks, does it also make sense to first request only the headers, then perform the `GET` only if the modification time indicates we need the new file?

**Comment by milliams** [comment]
Yes, that would be an improvement. There are two sources of slowness: 1) downloading the file and 2) parsing the file. The current solution only helps with the latter. Your suggestion would help with the former as well which would help.

**Comment by duncanmmacleod** [comment]
I think this was implemented by #31.

@milliams, do you have any plans for 1.8.1/1.9 release to include this?
