### ISSUE TITLE
Documentation  of Config paths is confusing

### ISSUE THREAD

**Issue by LocutusGrax** [sphinx-contrib/doxylink#57]
The documentaions text about the relative paths to Sphinx output path is incorrect. The first paramaeter, the tag file, paths is releative shinx build command.
`The keys of this dictionary must be lower-case. The prefix can be an absolute path or a path relative to [Sphinx' output directory](https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.outdir).`

**Comment by JasperCraeghs** [comment]
The content is technically already correct, but I see how it can be confusing. I will improve the wording. Thank you for creating this issue!
