### ISSUE TITLE
TypeError: 'dict_values' object does not support indexing

### ISSUE THREAD

**Issue by SteinHeselmans** [sphinx-contrib/doxylink#6]
using doxylink 1.4 on python 3.5, with sphinx 1.6.5

Exception occurred:
  File "/usr/local/lib/python3.5/dist-packages/sphinxcontrib/doxylink/doxylink.py", line 254, in find_url2
    return return_from_mapping(no_templates_list.values()[0], normalised_arglist)
TypeError: 'dict_values' object does not support indexing

[sphinx-err-kpi30nlv.log](https://github.com/sphinx-contrib/doxylink/files/1535582/sphinx-err-kpi30nlv.log)

**Comment by milliams** [comment]
Ah, yes, This is another one of those Python 2 to 3 errors. The easiest fix to this is to convert the result from `values()` to a list before indexing. There're a few other places in that function where this needs fixing too.
